GET http://localhost:8000/boards


GET http://localhost:8000/boards/:1

POST http://lcoalhost:8000
Content-Type: application/json
{  

}

PUT http://localhost:8000

DELETE http://localhost:8000/boards/:1