GET http://localhost:8000/boards

GET http://localhost:8000/boards/:1

POST http://localhost:8000/boards
Content-Type: application/json
{
    "title": "테스트 게시글 제목",
    "contents": "테스트 게시글 내용",
    "writeId": "TestUser10"
}

PUT http://localhost:8000/boards/:1
Content-Type: application/json
{
    "title": "수정 게시글 제목",
    "contents": "수정 게시글 내용",
    "modifyId": "TestUser1"
}

DELETE http://localhost:8000/boards/:1