GET http://localhost:8000/cars
searchKey: car


GET http://localhost:8000/cars/:1
searchKey: car

POST http://localhost:8000/cars
searchKey: car
Content-Type: application/json

{
    "carName": "car2",
    "carEngineName": "V3"
}

GET http://localhost:8000/cars
searchKey: engine