spring:
    devtools:
        livereload:
            enabled: false
    profiles:
        active: local
    output:
        ansi:
            enabled: always

logging:
    level:
        org:
            springframework: INFO