INSERT INTO board(board_title,board_contents,write_id,modify_id,write_date,modify_date) VALUES("Test Board Title 1","Test Board Contents","TestUser1","TestUser10","2023-06-10","2023-06-22");
INSERT INTO board(board_title,board_contents,write_id,modify_id,write_date,modify_date) VALUES("Test Board Title 2","Test Board Contents","TestUser2","TestUser9","2023-06-11" ,"2023-06-23");
INSERT INTO board(board_title,board_contents,write_id,modify_id,write_date,modify_date) VALUES("Test Board Title 3","Test Board Contents","TestUser3","TestUser8","2023-06-12" ,"2023-06-24");
INSERT INTO board(board_title,board_contents,write_id,modify_id,write_date,modify_date) VALUES("Test Board Title 4","Test Board Contents","TestUser4","TestUser7","2023-06-13" ,"2023-06-25");
INSERT INTO board(board_title,board_contents,write_id,modify_id,write_date,modify_date) VALUES("Test Board Title 5","Test Board Contents","TestUser5","TestUser6","2023-06-14","2023-06-26");
INSERT INTO board(board_title,board_contents,write_id,write_date) VALUES("Test Board Title 6","Test Board Contents","TestUser6","2023-06-20");
INSERT INTO board(board_title,board_contents,write_id,write_date) VALUES("Test Board Title 7","Test Board Contents","TestUser7","2023-06-19");
INSERT INTO board(board_title,board_contents,write_id,write_date) VALUES("Test Board Title 8","Test Board Contents","TestUser9","2023-06-18");
INSERT INTO board(board_title,board_contents,write_id,write_date) VALUES("Test Board Title 9","Test Board Contents","TestUser9","2023-06-17");
INSERT INTO board(board_title,board_contents,write_id,write_date) VALUES("Test Board Title 10","Test Board Contents","TestUser10","2023-06-16");