ALTER TABLE order_item DROP FOREIGN KEY FK_OrderItemOrder;

DROP TABLE IF EXISTS `order`;
DROP TABLE IF EXISTS order_item;

CREATE TABLE IF NOT EXISTS `order`(
	order_id BIGINT NOT NULL AUTO_INCREMENT,
	order_name VARCHAR(20) NOT NULL,
	PRIMARY KEY(order_id)
);

CREATE TABLE IF NOT EXISTS order_item(
	item_id BIGINT NOT NULL AUTO_INCREMENT,
	order_id BIGINT NOT NULL,
	product_name VARCHAR(200) NOT NULL,
	PRIMARY KEY(item_id)
);

ALTER TABLE order_item
ADD CONSTRAINT FK_OrderItemOrder
FOREIGN KEY (order_id) REFERENCES `order`(order_id);